---

- name: install or update KDE
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ package_kde }}"
    - kdm
    - switchdesk
    - system-switch-displaymanager
  tags:
    - packages
    - online

- name: create subdirectories for KDE configurations
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750
  with_items:
    - /home/{{ username }}/.kde/share/config
    - /home/{{ username }}/.local/share/konsole
  tags:
    - directories

- name: configure KDE by placing kdeglobals
  copy:
    src: files/kdeglobals
    dest: /home/{{ username }}/.kde/share/config/kdeglobals
    backup: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640
  tags:
    - configs

- name: include custom desktop shortcuts
  lineinfile:
    path: /home/{{ username }}/.config/kglobalshortcutsrc
    create: yes
    backup: yes
    line: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640
  with_lines: echo "{{ lookup('file', 'files/shortcuts.kksrc') }}"
  tags:
    - configs

- name: include profile for konsole
  copy:
    src: files/konsole.profile
    dest: /home/{{ username }}/.local/share/konsole/custom.profile
    backup: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640
  tags:
    - configs

- name: include configurations for konsole
  copy:
    src: files/konsolerc
    dest: /home/{{ username }}/.config/konsolerc
    backup: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640
  tags:
    - configs
