---

- name: install workstation
  hosts: all
  gather_facts: true
  become: yes
  become_user: root
  roles:
    - bash
    - executables
    - docker
    - git
    - tmux
    - vim
    - gnome
    - onedrive


