---

- import_playbook: setup.yml

- name: install workstation
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  roles:
    - git
    - bash
    - executables
    - tmux
    - vim
    - role: gnome
      tags: [ gui ]
    - onedrive

