---

- name: group by OS distribution
  hosts: all
  tasks:
    - group_by:
        key: "{{ ansible_distribution|lower }}"
    - debug:
        msg: found OS distribution {{ ansible_distribution|lower }}

- name: install workstation
  hosts: all
  gather_facts: true
  become: yes
  become_user: root
  tasks:
    - include_vars: "{{ ansible_distribution|lower }}.yml"
  roles:
    - common
    - bash
    - executables
    - docker
    - git
    - tmux
    - vim
    - gnome
    - onedrive

