---

- name: install or update Gnome
  package:
    name: "{{ package_gnome }}"
    state: latest
  notify:
    - restart Gnome
  tags:
    - packages
    - online

- name: configure Gnome by using dconf
  shell: |
    export $(/usr/bin/dbus-launch)
    dconf load /
  args:
    stdin: "{{ lookup('file', 'files/dconf.ini') }}"
  tags:
    - configs

