---

- name: install or update Git
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - meld

import_role:
  name: dotfiles

- name: link imported Git configuration
  file:
    src: /home/{{ username }}/git/dotfiles/.gitconfig
    dest: /home/{{ username }}/.gitconfig-{{ username }}
    force: yes

- name: include imported Git configuration
  git_config:
    scope: global
    name: include.path
    value: /home/{{ username }}/.gitconfig-{{ username }}

- name: create user's Git directory
  file:
    path: /home/{{ username }}/git
    state: directory
    mode: 0750
    owner: "{{ username }}"
    group: "{{ username }}"

- name: download Git Bash prompt
  get_url:
    url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
    dest: /home/{{ username }}/.git-prompt.sh

- name: include Git Bash prompt in .bashrc
  lineinfile:
    path: /home/{{ username }}/.bashrc
    line: "source ~/.git-prompt.sh"
    create: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 750

- name: set Git Bash prompt modifiers in .bashrc
  lineinfile:
    path: /home/{{ username }}/.bashrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 750
  with_items:
    - line: "export GIT_PS1_SHOWDIRTYSTATE=1"
      regexp: "^export GIT_PS1_SHOWDIRTYSTATE="
    - line: "export GIT_PS1_SHOWUNTRACKEDFILES=1"
      regexp: "^export GIT_PS1_SHOWUNTRACKEDFILES="
    - line: 'export GIT_PS1_SHOWUPSTREAM="verbose"'
      regexp: "^export GIT_PS1_SHOWUPSTREAM="

- name: extend Bash prompt variable
  replace:
    path: /home/{{ username }}/.bashrc
    regexp: "export PS1=(.*)\\w(.*)"
    replace: 'export PS1=\1\w\[\033[0;35m\]$(__git_ps1 " (%s)")\2'
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 750

