---

- name: create user directory for executables
  file:
    path: /home/{{ username }}/bin/
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750

- name: copy executable files
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/bin/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750
  with_fileglob: files/*

- name: start script for adjusting brightness on reboot
  job: "while sleep 10; do /home/{{ username }}/bin/adjust-brightness.sh > /dev/null; done"

