---

- name: install or update Docker from web
  shell: curl -fsSL get.docker.com | bash
  when: 'RedHat' != {{ ansible_os_family }}

- name: add Docker repository
  command: dnf config-manager --add-repo "https://download.docker.com/linux/{{ ansible_distribution|lower }}/docker-ce.repo"
  when: 'RedHat' == {{ ansible_os_family }}

- name: install or update Docker from repository
  package:
    name: docker-ce
    state: latest
  when: 'RedHat' == {{ ansible_os_family }}

- name: start Docker service
  service:
    name: docker
    enabled: true
    state: started

- name: add user {{ username }} to Docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: determine latest version of Docker Compose
  shell: curl -fsSL "https://api.github.com/repos/docker/compose/releases/latest" | grep -Po '[^"]+/docker-compose-'$(uname -s)-$(uname -m)
  register: docker_compose_url

- name: download Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose

- name: set executable bit on Docker Compose
  file:
    path: /usr/local/bin/docker-compose
    mode: +x

- name: download bash completion for Docker Compose
  get_url:
    url: "https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose"
    dest: /etc/bash_completion.d/docker-compose

